# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DCMI Infrastructure Advisory Committee
description: > # this means to ignore newlines until next config
  This site houses meeting minutes, announcements, and documentation 
  for the Dublin Core Metatdata Initiative's Infrastructure Advisory Committee (DCMI-IAC).
twitter_username: DublinCore
github_username:  dcmi
baseurl: "/dcmi-iac"
paginate: 5

# Build settings
markdown: kramdown
gems: [jekyll-paginate]

# Prose.io settings
prose:
  rooturl: '_posts'
  siteurl: 'http://metaweidner.github.io/dcmi-iac/'
  relativeLinks: 'http://metaweidner.github.io/dcmi-iac/links.jsonp'
  media: 'media'
  ignore:
    - index.html
    - feed.xml
    - posts.html
    - links.jsonp
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "date"
        field:
          element: "text"
          label: "Date"
      - name: "categories"
        field:
          element: "text"
          label: "Categories"
          value: "minutes"
      - name: "author"
        field:
          element: "text"
          label: "Author"
      - name: "attendees"
        field:
          element: "text"
          label: "Attendees"
      - name: "regrets"
        field:
          element: "text"
          label: "Regrets"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: "true"
      # - name: "tags"
      #   field:
      #     element: "multiselect"
      #     label: "Add Tags"
      #     placeholder: "Choose Tags"
      #     options:
      #       - name: "Apples"
      #         value: "apples"
      #       - name: "Bananas"
      #         value: "bananas"
      #       - name: "Pears"
      #         value: "pears"
      #       - name: "Mangos"
      #         value: "mangos"
