# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DCMI Infrastructure Advisory Committee
description: > # this means to ignore newlines until next config
  This site houses meeting minutes, announcements, and documentation 
  for the Dublin Core Metatdata Initiative's Infrastructure Advisory Committee (DCMI-IAC).
twitter_username: DublinCore
github_username:  dcmi

# Build settings
markdown: kramdown
paginate: 2
