# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DCMI Infrastructure Advisory Committee
description: > # this means to ignore newlines until next config
  This site houses meeting minutes, announcements, and documentation 
  for the Dublin Core Metatdata Initiative's Infrastructure Advisory Committee (DCMI-IAC).
twitter_username: DublinCore
github_username:  dcmi
baseurl: "/dcmi-iac"
paginate: 5

# Build settings
markdown: kramdown
gems: [jekyll-paginate]

# Prose.io settings
prose:
  rooturl: '_posts'
  siteurl: 'http://metaweidner.github.io/dcmi-iac/'
  relativeLinks: 'http://metaweidner.github.io/dcmi-iac/links.jsonp'
  media: 'media'
  ignore:
    - index.html
    - feed.xml
    - posts.html
    - links.jsonp
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "year"
        field:
          element: "text"
          label: "Year"
          value: "2016"
      - name: "month"
        field:
          element: "select"
          label: "Month"
          placeholder: "Select a Month"
          options:
            - name: "January"
              value: "01"
            - name: "February"
              value: "02"
            - name: "March"
              value: "03"
            - name: "April"
              value: "04"
            - name: "May"
              value: "05"
            - name: "June"
              value: "06"
            - name: "July"
              value: "07"
            - name: "August"
              value: "08"
            - name: "September"
              value: "09"
            - name: "October"
              value: "10"
            - name: "November"
              value: "11"
            - name: "December"
              value: "12"
      - name: "day"
        field:
          element: "select"
          label: "Day"
          placeholder: "Select a Day"
          options:
            - name: "1"
              value: "01"
            - name: "2"
              value: "02"
            - name: "3"
              value: "03"
            - name: "4"
              value: "04"
            - name: "5"
              value: "05"
            - name: "6"
              value: "06"
            - name: "7"
              value: "07"
            - name: "8"
              value: "08"
            - name: "9"
              value: "09"
            - name: "10"
              value: "10"
            - name: "11"
              value: "11"
            - name: "12"
              value: "12"
            - name: "13"
              value: "13"
            - name: "14"
              value: "14"
            - name: "15"
              value: "15"
            - name: "16"
              value: "16"
            - name: "17"
              value: "17"
            - name: "18"
              value: "18"
            - name: "19"
              value: "19"
            - name: "20"
              value: "20"
            - name: "21"
              value: "21"
            - name: "22"
              value: "22"
            - name: "23"
              value: "23"
            - name: "24"
              value: "24"
            - name: "25"
              value: "25"
            - name: "26"
              value: "26"
            - name: "27"
              value: "27"
            - name: "28"
              value: "28"
            - name: "29"
              value: "29"
            - name: "30"
              value: "30"
            - name: "31"
              value: "31"
      - name: "category"
        field:
          element: "select"
          label: "Category"
          placeholder: "Select a Category"
          options:
            - name: "Minutes"
              value: "minutes"
            - name: "Announcements"
              value: "announcements"
      - name: "author"
        field:
          element: "text"
          label: "Author"
      - name: "attendees"
        field:
          element: "text"
          label: "Attendees"
      - name: "regrets"
        field:
          element: "text"
          label: "Regrets"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: "true"
      # - name: "tags"
      #   field:
      #     element: "multiselect"
      #     label: "Add Tags"
      #     placeholder: "Choose Tags"
      #     options:
      #       - name: "Apples"
      #         value: "apples"
      #       - name: "Bananas"
      #         value: "bananas"
      #       - name: "Pears"
      #         value: "pears"
      #       - name: "Mangos"
      #         value: "mangos"
